### ISSUE TITLE
Possibility to use /usr/local/etc/rc.d/qemu-guest-agent

### ISSUE THREAD

**Issue by michaelr0** [Weehooey/pfSense-scripts#2]
Hi @billzee 

I'm not sure if this is standard, but I just followed these steps and found that there seems to be an existing file for me called `/usr/local/etc/rc.d/qemu-guest-agent`, on `2.7.1-RELEASE` after `pkg install qemu-guest-agent`

In my particular case, I have been able to replace the below

```sh
cat > /usr/local/etc/rc.d/qemu-agent.sh << EOF
#!/bin/sh
sleep 3
service qemu-guest-agent start
EOF

chmod +x /usr/local/etc/rc.d/qemu-agent.sh
```

with `ln -s /usr/local/etc/rc.d/qemu-guest-agent /usr/local/etc/rc.d/qemu-guest-agent.sh` and it appears to be working.

**Comment by billzee** [comment]
Hi @michaelr0 

Thanks for the note. I will take a look and maybe we can update the script. 

Cheers

Bill

**Comment by billzee** [comment]
Hi @michaelr0 

Yes, `/usr/local/etc/rc.d/qemu-guest-agent` is a file that is installed with the QEMU guest package package. 

With `qemu_guest_agent_enable="YES"` the agent should start on its own. However, `/usr/local/etc/rc.d/qemu-agent.sh` script was a workaround for those where it was not starting (thus the `sleep 3`). 

You may be able to eliminate that script entirely. At some point, I will do some testing. It might not be needed any longer.

**Comment by michaelr0** [comment]
Thanks, @billzee I used the symlink because it looks like qemu-guest-agent is not started using the default startup script, as the file is not loaded by rc init, because it does not have the .sh extension, the symlink solves that loading issue for me :)
